#!/bin/sh

rm -rf dist/

gulp

cd dist
zip cybergrid-13.zip *
cd ..

wc -c *.js
echo "----------------------------"
du -sh dist/* | grep 'js'
du -sh dist/* | grep 'zip'
wc -c dist/*.js
wc -c dist/*.zip
